[project]
name = "dynamic-modeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fabian Roth", email = "fabian.roth.24@stud.tu-darmstadt.de" }
]
requires-python = ">=3.12"
dependencies = [
    "diffrax>=0.7.0",
    "klax@git+https://github.com/Drenderer/klax#egg=a6573058a3295b403d11d526055f55cb2ec8515b",
    "matplotlib>=3.10.3",
    "notebook>=7.4.3",
]

[tool.uv.sources]
klax = { git = "https://github.com/Drenderer/klax", rev = "a6573058a3295b403d11d526055f55cb2ec8515b" }

[project.scripts]
dynamic-modeling = "dynamic_modeling:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
